name: flutter_fruit_hub
description: Fruit Hub App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  google_maps_flutter: ^2.0.6
  lottie: ^1.0.1
  url_launcher: ^6.0.7
  equatable: ^2.0.3
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  firebase_analytics: ^8.1.2
  firebase_remote_config: ^0.10.0+2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.6

  intl: ^0.17.0
  flutter_clean_architecture: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.4
  bloc_test: ^8.0.2
  mocktail: ^0.1.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/animation/

  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    -  family: Brandon-Grotesque
       fonts:
         - asset: fonts/brandon-grotesque-regular.otf
           weight: 400
         -  asset: fonts/brandon-grotesque-italic.otf
            style: italic
         - asset: fonts/brandon-grotesque-medium.otf
           weight: 500

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
