const int FIRST_INDEX = 0;

const int NOT_AN_INDEX = -1;

const double DEFAULT_APP_BAR_PERCENTAGE_HEIGHT = 0.15;

const int DEFAULT_AVAILABLE_QUANTITY_FRUIT = 999;

const int ONE_ITEM = 1;

const int TRACK_ORDER_STAGE_ORDER_TAKEN = 1;

const int TRACK_ORDER_STAGE_ORDER_PREPARED = 2;

const int TRACK_ORDER_STAGE_ORDER_DELIVERED = 3;

const int TRACK_ORDER_STAGE_ORDER_RECEIVED = 4;

const int TRACK_ORDER_STAGE_ORDER_COMPLETE = 5;
